version: '3'
services:
  mongo_db:
    image: mongo
    environment:
       - MONGO_INITDB_ROOT_USERNAME:"root"
       - MONGO_INITDB_ROOT_PASSWORD:"rootpassword"
    ports:
       - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
       - 8081:8081
    environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME:"admin"
       - ME_CONFIG_MONGODB_ADMINPASSWORD:"adminpassword"
       - MONGO_INITDB_DATABASE:ethans-db  
